### ISSUE TITLE
Duplicated modules

### ISSUE THREAD

**Issue by tomitrescak** [isaul32/ckeditor5-math#110]
Hello, looks fantastic your plugin, but I'm getting the following error when addin it to my build:

```
version.js:152 Uncaught CKEditorError: ckeditor-duplicated-modules
Read more: https://ckeditor.com/docs/ckeditor5/latest/support/error-codes.html#error-ckeditor-duplicated-modules
    at version.js:152:11
    at ckeditor.js:6:2002156
    at universalModuleDefinition:11:1
    at universalModuleDefinition:9:37
    at universalModuleDefinition:1:1
```

All I did was to add your plugin. Thanks!

**Comment by tony** [comment]
Hi, I am assuming this is resolved / this may have been due to pinning?

This didn't include information as to what version you were using at the time and what version of ckeditor5-math it was - but the ckeditor5-math version would need to match ckeditor5.

I am currently cleaning up issues - if this is still an problem please let me know. I will close for now.
