### ISSUE TITLE
Publish latest versions in npm

### ISSUE THREAD

**Issue by lupari** [isaul32/ckeditor5-math#114]
Hi. 

Looking at ckeditor5-math releases here in github it seems that the latest is 39.0.1. However that can't be installed via npm. The latest version available there is 36.0.2. Would it be possible to publish the missing versions to npm? I'd need a version compatible with ckeditor5 39.x. and I understood that ckeditor5-math's version should match that of ckeditor5.

**Comment by naslundx** [comment]
Also wondering about this, as there seem to be active releases on github, but not on npm. @tony ?

**Comment by tony** [comment]
Hi!

@lupari @naslundx They are at [https://www.npmjs.com/package/@isaul32/ckeditor5-math](@isaul32/ckeditor5-math)

So the package is at `@isaul32/ckeditor5-math` instead of `ckeditor5-math`.

Some backstory:
- https://github.com/ckeditor/ckeditor5-package-generator/issues/139
- https://github.com/isaul32/ckeditor5-math/pull/83/files#r1134754172

It may be possible with the merge of https://github.com/ckeditor/ckeditor5-package-generator/pull/145 in https://github.com/ckeditor/ckeditor5-package-generator/commit/a820183289fa73c2bba14f98dbfe2ac1ee3a085e and publish in ckeditor5-package-generator in [v1.0.0](https://github.com/ckeditor/ckeditor5-package-generator/releases/tag/v1.0.0), we can use `ckeditor5-math` again.

I can elaborate more over the weekend.

**Comment by naslundx** [comment]
Fantastic! Thanks @tony !

**Comment by tony** [comment]
(I am clearing out issues)

If there is interest in publishing back to `ckeditor5-math` from `@isaul32/ckeditor5-math`, we can. I propose creating a new issue if interest does continue.
