### ISSUE TITLE
Prettier config? Format files? 2 space indentation?

### ISSUE THREAD

**Issue by tony** [isaul32/ckeditor5-math#30]
Any opinions on adopting a [prettier](https://prettier.io/) / formatting config and running it on the codebase?

(I don't have any style opinions, other than using 2 space indentation and using prettier as a formatter)

**Comment by isaul32** [comment]
Personally I don't like to do formatting manually. So that is a good idea but I would also prefer use same formatting as CKEditor uses. They are using their own `eslint-config-ckeditor5` rules. Maybe we could use prettier with `eslint-config-prettier` plugin and then use same eslint rules with prettier?

**Comment by tony** [comment]
I brought up a prettier for CKEditor here: https://github.com/ckeditor/ckeditor5/issues/9377

we'll see what develops
